name: Cache Dependencies

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Cache dependencies
        uses: actions/cache@v4
        id: cache-deps
        with:
          path: node_modules
          key: cache-90ae209
          
      - name: prime-cache-90ae209
        run: |
          if [ "${{ steps.cache-deps.outputs.cache-hit }}" == 'true' ]; then
            echo "Cache hit - dependencies restored"
          else
            echo "Cache miss - dependencies will be cached"
            npm install
          fi
